const API_BASE="http://127.0.0.1:3001";
let roster=[];
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
async function getJSON(path,options={}){const r=await fetch(API_BASE+path,options);let data={};try{data=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(data.error||`HTTP ${r.status}`),{status:r.status,data});return data}
function loadForm(){const e=$("employeeSelect"),s=$("shiftSelect");e.innerHTML=roster.map(x=>`<option value="${esc(x.employee_id)}">${esc(x.name)} (${esc(x.employee_id)})</option>`).join("");refreshShifts();e.addEventListener("change",refreshShifts)}
function refreshShifts(){const id=$("employeeSelect").value;const e=roster.find(x=>x.employee_id===id);$("shiftSelect").innerHTML=(e?.shifts||[]).map(s=>`<option value="${esc(s.shift_id)}">${esc(s.shift_id)} — ${esc(s.date)} ${esc(s.start_time)}–${esc(s.end_time)}</option>`).join("")||"<option value=\"\">No shifts</option>"}
async function loadRoster(){try{const d=await getJSON("/roster");roster=d.roster||[];loadForm();$("rosterGrid").innerHTML=roster.map(e=>`<article class=card><strong>${esc(e.name)}</strong><small>${esc(e.role)} · ${esc(e.department)}</small>${e.shifts.map(s=>`<div class=shift>${esc(s.shift_id)} · ${esc(s.date)} · ${esc(s.start_time)}–${esc(s.end_time)}</div>`).join("")}</article>`).join("")}catch(err){$("rosterGrid").innerHTML=`<div class=card>Roster unavailable: ${esc(err.message)}</div>`}}
async function loadDecisions(){try{const d=await getJSON("/decisions");$("decisionList").innerHTML=(d.decisions||[]).map(x=>`<div class=decision><div><strong>${esc(x.request_id)}</strong> · ${esc(x.from_employee)} → ${esc(x.shift_id)}<br><small>${esc(x.explanation)}</small></div><div class=${x.status==="pending_approval"?"ok":"bad"}>${esc(x.status)}</div></div>`).join("")||"<div class=card>No decisions yet.</div>"}catch(err){$("decisionList").innerHTML=`<div class=card>Decision stream unavailable: ${esc(err.message)}</div>`}}
$("swapForm").addEventListener("submit",async ev=>{ev.preventDefault();const out=$("result");out.classList.remove("hidden");out.textContent="Running arbitration…";try{const d=await getJSON("/swap-request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({from_employee:$("employeeSelect").value,shift_id:$("shiftSelect").value,reason_text:$("reason").value.trim()})});out.innerHTML=`<strong class="${d.cedar_decision==="Decision::Allow"||d.cedar_decision==="Allow"?"ok":"bad"}">${esc(d.status||"decision")}</strong><p>${esc(d.explanation||d.reason||"")}</p><p>Cedar: ${esc(d.cedar_decision||"n/a")} · Eligible: ${esc(d.eligible_partner_count??0)}</p>`;loadDecisions()}catch(err){out.innerHTML=`<strong class=bad>REQUEST REJECTED</strong><p>${esc(err.data?.reason||err.message)}</p><p>Cedar: ${esc(err.data?.cedar_decision||"not reached")}</p>`}});
loadRoster();loadDecisions();
